### PR TITLE
feat: Adding VSCode for web-browser, alongside Jupyterlab.

### PR DESCRIPTION
**Pull request by aleksandrmelnikov**
- Note that python and jupyter lab notebook previewer are installed
during dockerfile build

fixes #https://github.com/onepanelio/core/issues/609

### CODE REVIEW

**Comment by rushtehrani** [comment]
@aleksandrmelnikov we also need to add `onepanel-sdk`, see [this JupyterLab commit](https://github.com/onepanelio/templates/commit/ba99ef580bbe00cc3a4e377b288eeaf18dc4077e) for reference.

Also, both this and the updated JupyterLab I referenced need to be added to migrations in Onepanel.

**Comment by rushtehrani** [comment]
We need to remove the JupyterLab container here and also update the directory/Dockerfile name to `vscode`.

**Comment by rushtehrani** [comment]
We actually don't need the "VS Code Jupyter Notebook Previewer" extension, the python extension already includes a full renderer.

**Comment by rushtehrani** [comment]
Switched from CPU to GPU and my data is now gone, we need to make sure data is persisting on the attached volume.

**Comment by aleksandrmelnikov** [comment]
> @aleksandrmelnikov we also need to add `onepanel-sdk`, see [this JupyterLab commit](https://github.com/onepanelio/templates/commit/ba99ef580bbe00cc3a4e377b288eeaf18dc4077e) for reference.
> 
> Also, both this and the updated JupyterLab I referenced need to be added to migrations in Onepanel.

Done.

**Comment by aleksandrmelnikov** [comment]
> We need to remove the JupyterLab container here and also update the directory/Dockerfile name to `vscode`.

Done

**Comment by aleksandrmelnikov** [comment]
> We actually don't need the "VS Code Jupyter Notebook Previewer" extension, the python extension already includes a full renderer.

Done

**Comment by aleksandrmelnikov** [comment]
> Switched from CPU to GPU and my data is now gone, we need to make sure data is persisting on the attached volume.

This is ready for review.

**Comment by rushtehrani** [comment]
@aleksandrmelnikov need to remove [this section](https://github.com/onepanelio/templates/blob/master/workspaces/README.md#jupyterlab-and-vscode) from the Workspaces README as well.

**Comment by aleksandrmelnikov** [comment]
> @aleksandrmelnikov need to remove [this section](https://github.com/onepanelio/templates/blob/master/workspaces/README.md#jupyterlab-and-vscode) from the Workspaces README as well.

Fixed

**Pull request merged**
