### PR TITLE
update: cvat tags which fixes an issue with data upload and node pool UI

### PR DESCRIPTION
**Pull request by savan77**
The new image fixes following issues:
https://github.com/onepanelio/core/issues/654
https://github.com/onepanelio/core/issues/651

### CODE REVIEW

**Comment by rushtehrani** [comment]
@savan77 can you coordinate with @Vafilor to make sure this is updated to the latest template before we merge it?

**Comment by savan77** [comment]
@Vafilor can you provide me latest cvat and filesyncer images so that I can update the PR?

**Comment by Vafilor** [comment]
@savan77 Sure thing. The latest images are

* cvat: onepanel/cvat:0.14.0_cvat.1.0.0
* cvat-ui: onepanel/cvat-ui:0.14.0_cvat.1.0.0
* filesyncer: onepanel/filesyncer:s3

**Comment by savan77** [comment]
Thanks @Vafilor . @rushtehrani I have updated the CVAT template with latest tags.

**Pull request merged**
